### ISSUE TITLE
Filters/Filter Chains with several inputs and/or outputs

### ISSUE THREAD

**Issue by rbejar** [IAAA-Lab/gdtc#3]
E.g. producing a SHP file and a CSV with some statistics on its data, or a PDF with a map plot of this file, in the same filter / filter chain.

**Comment by Melic93** [comment]
FilterVector basefilter created + Multifilters extending FilterVector class created + tests.
I'll extend the functionality of this filter to produce multiple outputs, but that will be a different issue.
