### ISSUE TITLE
Dockerfile for the gdtc image should use conda and not pip to manage packages

### ISSUE THREAD

**Issue by rbejar** [IAAA-Lab/gdtc#30]
And, of course, the gtc_conda.yml file shared in the repository. It may not be necessary to install gdal for instance, as conda should take care.

**Comment by Melic93** [comment]
I don't agree with that. Using Conda inside docker is like using docker inside of docker. There is no need to create a virtual environment inside docker, which is an isolated container running our project. Conda is great for local development, but I don't think we should use it in production. If you are just thinking about dependencies management, pip is enough.
Another problem is that Conda or Anaconda are too big and not recommended for docker images which should stay minimal.

**Comment by fjlopez** [comment]
Have you tested the [Anaconda maintained Docker images](https://hub.docker.com/r/continuumio/anaconda/)?

**Comment by Melic93** [comment]
I didn't, because I'm using a minimal python 3.7 manintained base image which includes pip. Also, the image you linked is using python 2.7, which is outdated.
It's not a definitive dockerfile yet, but I don't think we need Conda at all.

**Comment by rbejar** [comment]
I want conda just as a package manager, not necessarily for the virtual environment. Unlike pip, which is what is being used right now in the docker image, conda can manage non-python packages as well, which is really helpful to install the right version of the compiled libraries that some python packages use, specially when the installation of them is tricky, what is true for a number of GIS packages that we will be using. My experience with conda has been in general much better than my experience with pip for scientific python in general.
