### ISSUE TITLE
Fix tests, at least to make them run in TravisCI

### ISSUE THREAD

**Issue by rbejar** [IAAA-Lab/gdtc#32]

**Comment by rbejar** [comment]
I have created another repository with the datasets <https://github.com/IAAA-Lab/gdtc-test-data> used in the tests in order to facilitate the access to those datasets both from the developer environments and from travis.

**Comment by Melic93** [comment]
Docker + Conda integration with Travis CI is done, but I still have to finish some code so tests can pass.

**Comment by Melic93** [comment]
Travis takes a lot of time to build the docker image and install conda + dependencies + run tests.

**Comment by rbejar** [comment]
~10 minutes is not optimal, but it is not that terrible. We can explore the options that Travis CI provides to cache things (at least the built docker image) but I would not consider this a priority for now.
